### PR TITLE
Update metrics query

### PR DESCRIPTION
**Pull request by tzumainn**
Recent versions no longer include metrics such as
kube_pod_init_container_resource_limits_cpu_cores; instead they have kube_pod_init_container_resource_limits, with individual results having a unit attribute to filter by.

### CODE REVIEW

**Review by computate — CHANGES_REQUESTED** [review]
It would be good to also update the references to these metrics in the README.md file since they have changed.

**Comment by tzumainn** [comment]
> It would be good to also update the references to these metrics in the README.md file since they have changed.

Ah, great catch! I've updated the README - let me know if you spot anything else!

**Review by computate — CHANGES_REQUESTED** [review]
Looks like there is another place in the README that show the old metrics: 
```
| ncpus          | *kube_pod_init_container_resource_requests_cpu_cores*  |
| req_cpus       | *kube_pod_init_container_resource_limits_cpu_cores*    |
| req_mem        | *kube_pod_init_container_resource_limits_memory_bytes* |
```

**Comment by tzumainn** [comment]
> Looks like there is another place in the README that show the old metrics:
> 
> ```
> | ncpus          | *kube_pod_init_container_resource_requests_cpu_cores*  |
> | req_cpus       | *kube_pod_init_container_resource_limits_cpu_cores*    |
> | req_mem        | *kube_pod_init_container_resource_limits_memory_bytes* |
> ```

Whoops - fixed as well! I've searched for further uses of the string, so I think that should be all of them. Thanks for checking!

**Review by computate — APPROVED** [review]

**Pull request merged**
